[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
crowdfunding = "Fs4wNeXAJKypKodn4kbDs7nmdJeFB6emVY2Ntj3FLqzt"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
